# "auto" tells nginx to create one worker per CPU.
worker_processes auto;

# The events block tells nginx how to accept connections. 
# worker_connections is the number of simultaneous connections each worker can handle.
events {
    worker_connections 1024;
}

# The http block contains the configuration for the HTTP server.
http {
    # An upstream block lists the servers nginx can send requests to.
    # Each new request goes to the next server (round-robin).
    # nginx is launched after the two Flask servers are running.
    # At launch, a script replaces the contents of the block with the 
    # actual server addresses.
    upstream flask_app {
        UPSTREAM_SERVERS
    }

    # A server block defines a web server instance.
    server {
        listen 80;

        # A location block matches any URL that starts with the specified URL.
        # `/` matches every request.
        location / {
            # Forward the request to the flask_app list (defined above). This
            # causes nginx to distribute each request across all servers using
            # round-robin.
            proxy_pass http://flask_app;
            # Set the Host header so that Flask sees the web server name in the
            # original request and not flask_app (the pool name).
            proxy_set_header Host $host;
        }
    }
}
