# "auto" tells nginx to create one worker per CPU.
worker_processes auto;

http {
    # An upstream block lists the servers nginx can send requests to.
    # Each new request goes to the next server (round-robin).
    # nginx is launched after the two Flask servers are running.
    # The userdata script replaces UPSTREAM_SERVERS with a list of those servers.
    upstream flask_app {
        UPSTREAM_SERVERS
    }

    # A server block defines a web server instance.
    server {
        listen 80;

        # A location block matches any URL that starts with the specified URL.
        # `/` matches every request.
        location / {
            # Forward the request to the flask_app list (defined above). This
            # causes nginx to distribute each request across all servers using
            # round-robin.
            proxy_pass http://flask_app;
            # Set the Host header so that Flask sees the web server name in the
            # original request and not flask_app (the pool name).
            proxy_set_header Host $host;
        }
    }
}
